# Generated by Django 5.0.6 on 2024-05-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner_email',
            field=models.EmailField(default='noemeail@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner_name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner_phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner_photo',
            field=models.ImageField(default='default_owner.jpg', upload_to='owner_photos/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(default='default_hotel.jpg', upload_to='hotel_photos/'),
        ),
        migrations.AddField(
            model_name='room',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='max_occupancy_adults',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='max_occupancy_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Standard Room', max_length=100),
        ),
    ]
