# Generated by Django 5.0.6 on 2024-06-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='hotel',
        ),
        migrations.AlterField(
            model_name='room',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='admin_app.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_occupancy_adults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_occupancy_children',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupancy',
            field=models.IntegerField(default=0),
        ),
    ]
